### ISSUE TITLE
The usage of `since` would make test reports better readable.

### ISSUE THREAD

**Issue by maraisr** [mawrkus/js-unit-testing-guide#3]
If you take a look at this test case:

```js
describe('A set of functionalities', () => {
  it('should do something nice', () => {
   expect(myVar).toBe(true);
  });
});
```

if this test fails, then your report will say something along the lines of:

> expected undefined to be true

which doesn't mean anything.

Would be much nicer to use [Jasmine Custom Messages](https://github.com/avrelian/jasmine2-custom-message). Where your tests would start to look like this:

```js
describe('A set of functionalities', () => {
  it('should do something nice', () => {
   since('i have a boolean variable named myVar with a value of true')
      .expect(myVar).toBe(true);
  });
});
```

And your typical report would read on a failure: 

> A set of functionalities should do something nice I have a boolean I have a boolean variable named myVar with a value of true FAILED

Basically creating much more approachable error reports that mean something later in the future. And motivating the notion of creating meaningful tests.

What are your thoughts?

**Comment by mawrkus** [comment]
Hi! My thoughts are:

1. The guide is not meant to be bound to a specific library/testing framework. The examples are illustrated with Jasmine (because it's widely used & has a nice chainable syntax) but they could also had been written assuming the usage of Mocha, Tape, Jest, Sinon or any another library. The main ambition is to present some useful guidelines that can hopefully help developers to write better tests, regardless of the testing tools used.

2. I think the example you take produces a report that doesn't mean anything because the example itself doesn't mean much ;) But if we take something closer to a real case, we could have:
`
describe('the ads manager', () => {
  it('should mark the ad as displayed', () => {
     // const isAdDisplayed = ...;
     expect(isAdDisplayed).toBe(true);
  });
});
`

With a better description, the report starts to be more explicit. Also, the spec title does not have to mention the name of the variable, which is a low level detail in regards to the functionality tested. At the end, if something fails, the stack trace would be your best friend to fix the code, the report would not be sufficient.

**Comment by maraisr** [comment]
You make an interesting point, I mean there are a vast amount of different scenarios one could argue for or against.  I guess I didn't do a great job of articulating my point; I merely wanted to stress the point that with `since` you gain much better log messages than a simple "cannot call function of undefined".

It's like - yeah you the describe-it notion works really well to describe what you're testing, but then it's also important to describe what you're expecting.

Like you might want to test if the ad manager displayed, and then you're expecting a property to be set. So have your "the ads manager should mark the ad as displayed", with an "isAdDisplayed property to be true". Extending the premise of "what", and "how". What being the describe-it, and the since being the how.

**Comment by mawrkus** [comment]
Indeed, unless if the "how" is a technical detail, and/or subject to changes/refactoring. In the example, the one thing I need to be sure is that the ad manager does its job properly. If the "how" is really important, I would explicitly state it in the spec title ("it should set the isAdDisplayed variable to true").

**Comment by maraisr** [comment]
Do you mean "it should have the isAdDisplayed variable set to true"?

**Comment by mawrkus** [comment]
...or something similar ;)
